const cars=[
 {name:'2022 Toyota 4Runner TRD Pro',dealer:'Apex Motors',type:'SUV',year:2022,miles:'28,412 mi',price:44990,features:['AWD','Certified'],img:'https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&w=900&q=85'},
 {name:'2021 BMW M4 Competition',dealer:'Northline Auto',type:'Coupe',year:2021,miles:'16,208 mi',price:73900,features:['Certified'],img:'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=900&q=85'},
 {name:'2023 Rivian R1T Adventure',dealer:'Evergreen',type:'Truck',year:2023,miles:'9,840 mi',price:67990,features:['AWD','Electric'],img:'https://images.unsplash.com/photo-1620891549027-942fdc95d3f5?auto=format&fit=crop&w=900&q=85'},
 {name:'2024 Volvo XC60 Recharge',dealer:'Hatchback',type:'SUV',year:2024,miles:'4,102 mi',price:58900,features:['AWD','Electric','Certified'],img:'https://images.unsplash.com/photo-1616422285623-13ff0162193c?auto=format&fit=crop&w=900&q=85'},
 {name:'2022 Porsche Taycan 4S',dealer:'Apex Motors',type:'Sedan',year:2022,miles:'11,780 mi',price:92900,features:['AWD','Electric'],img:'https://images.unsplash.com/photo-1611651338412-8403fa6e3599?auto=format&fit=crop&w=900&q=85'},
 {name:'2023 Toyota Land Cruiser',dealer:'Northline Auto',type:'SUV',year:2023,miles:'7,214 mi',price:62400,features:['AWD','Certified'],img:'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=900&q=85'},
 {name:'2025 Tesla Model Y Long Range',dealer:'Evergreen',type:'SUV',year:2025,miles:'1,240 mi',price:58900,features:['AWD','Electric'],img:'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=900&q=85'},
 {name:'2024 Mercedes-Benz GLE 450',dealer:'Apex Motors',type:'SUV',year:2024,miles:'5,890 mi',price:74500,features:['AWD','Certified'],img:'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=900&q=85'},
 {name:'2025 Honda CR-V Hybrid',dealer:'Hatchback',type:'SUV',year:2025,miles:'820 mi',price:41200,features:['AWD','Electric'],img:'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=85'},
 {name:'2024 Ford F-150 Lariat',dealer:'Northline Auto',type:'Truck',year:2024,miles:'12,140 mi',price:56900,features:['AWD','Certified'],img:'https://images.unsplash.com/photo-1592840496694-26d035b52b48?auto=format&fit=crop&w=900&q=85'},
 {name:'2025 Kia EV6 GT-Line',dealer:'Evergreen',type:'Sedan',year:2025,miles:'430 mi',price:51900,features:['AWD','Electric'],img:'https://images.unsplash.com/photo-1651058520821-9b4e5fbcf9f4?auto=format&fit=crop&w=900&q=85'},
 {name:'2024 Audi Q5 Premium',dealer:'Apex Motors',type:'SUV',year:2024,miles:'8,670 mi',price:49800,features:['AWD','Certified'],img:'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=900&q=85'},
 {name:'2023 Lexus RX 350h',dealer:'Hatchback',type:'SUV',year:2023,miles:'14,280 mi',price:53700,features:['AWD','Electric','Certified'],img:'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=85'}
];
const extraMakes=[['Honda','Civic','Sedan'],['Honda','Pilot','SUV'],['Nissan','Altima','Sedan'],['Nissan','Rogue','SUV'],['Hyundai','Tucson','SUV'],['Hyundai','Elantra','Sedan'],['Kia','Sportage','SUV'],['Kia','Telluride','SUV'],['Ford','Mustang','Coupe'],['Ford','Explorer','SUV'],['Chevrolet','Tahoe','SUV'],['Chevrolet','Silverado','Truck'],['Jeep','Wrangler','SUV'],['Jeep','Grand Cherokee','SUV'],['Mazda','CX-5','SUV'],['Subaru','Outback','SUV'],['Volkswagen','Tiguan','SUV'],['Lexus','ES 350','Sedan'],['Acura','MDX','SUV'],['Tesla','Model 3','Sedan']];
extraMakes.forEach(([make,model,type],i)=>cars.push({name:`2024 ${make} ${model}`,dealer:['Apex Motors','Northline Auto','Evergreen','Hatchback'][i%4],type,year:2024,miles:`${(3200+i*417).toLocaleString()} mi`,price:32000+i*1800,features:type==='SUV'?['AWD','Certified']:['Certified'],img:'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=900&q=85'}));
const catalogImages=['https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=900&q=85'];cars.slice(6).forEach((c,i)=>c.img=catalogImages[i%catalogImages.length]);
let activeDealer='all', saved=new Set(), compare=new Set(), visibleCount=999;
const grid=document.querySelector('#carGrid');
function money(n){return '₦'+Math.round(n*1500).toLocaleString('en-NG')}
function render(){let q=document.querySelector('#search').value.toLowerCase(), make=document.querySelector('#make').value, price=document.querySelector('#price').value, bodies=[...document.querySelectorAll('.body-filter:checked')].map(x=>x.value), feats=[...document.querySelectorAll('.feature-filter:checked')].map(x=>x.value), min=document.querySelector('#yearMin').value,max=document.querySelector('#yearMax').value; let list=cars.filter(c=>(activeDealer==='all'||c.dealer===activeDealer)&&(!q||c.name.toLowerCase().includes(q)||c.dealer.toLowerCase().includes(q))&&(make==='all'||c.name.includes(make))&&(!bodies.length||bodies.includes(c.type))&&(!feats.length||feats.every(f=>c.features.includes(f)))&&(price==='all'||price==='under30'&&c.price<30000||price==='30to50'&&c.price>=30000&&c.price<=50000||price==='over50'&&c.price>50000)&&(min==='all'||c.year>=+min)&&(max==='all'||c.year<=+max)); const sort=document.querySelector('#sort').value;if(sort==='price-low')list.sort((a,b)=>a.price-b.price);if(sort==='price-high')list.sort((a,b)=>b.price-a.price);if(sort==='year-new')list.sort((a,b)=>b.year-a.year);document.querySelector('.inventory-head h2').textContent=make==='all'?'Cars near San Francisco':`${make} cars near San Francisco`;grid.innerHTML=list.length?list.slice(0,visibleCount).map(card).join(''):'<div class="empty-state">No cars found. Try another make or remove a filter.</div>';lucide.createIcons();}
function card(c){return `<article class="car-card"><div class="car-image"><img src="${c.img}" alt="${c.name}"><button class="save-car ${saved.has(c.name)?'saved':''}" data-save="${c.name}" aria-label="Save vehicle"><i data-lucide="heart" ${saved.has(c.name)?'fill="currentColor"':''}></i></button></div><div class="card-body"><div class="dealer-line"><span>${c.dealer}</span><span class="verified"><i data-lucide="badge-check"></i> Verified</span></div><h3 class="car-name">${c.name}</h3><div class="car-meta"><span>${c.year}</span><span>${c.miles}</span><span>${c.type}</span></div><div class="price-row"><div><div class="price">${money(c.price)}</div><div class="payment">Est. ${money(Math.round(c.price/60))}/mo</div></div><label class="compare-check"><input type="checkbox" data-compare="${c.name}" ${compare.has(c.name)?'checked':''}> Compare</label></div><div class="card-actions"><button class="outline-btn" data-details="${c.name}">View details</button><button class="solid-btn" data-contact="${c.name}">Contact dealer</button></div></div></article>`}
function updateTray(){document.querySelector('#compareCount').textContent=compare.size;document.querySelector('#compareTray').classList.toggle('visible',compare.size>0);document.querySelector('#compareBtn').disabled=!compare.size}
document.addEventListener('click',e=>{let save=e.target.closest('[data-save]');if(save){let n=save.dataset.save;saved.has(n)?saved.delete(n):saved.add(n);render();toast(saved.has(n)?'Vehicle saved':'Removed from saved vehicles')}let cmp=e.target.closest('[data-compare]');if(cmp){if(cmp.checked&&compare.size>=3){cmp.checked=false;toast('You can compare up to 3 vehicles');return}cmp.checked?compare.add(cmp.dataset.compare):compare.delete(cmp.dataset.compare);updateTray()}if(e.target.closest('.dealer-tab')){document.querySelectorAll('.dealer-tab').forEach(x=>x.classList.remove('active'));let b=e.target.closest('.dealer-tab');b.classList.add('active');activeDealer=b.dataset.dealer;render()}if(e.target.closest('#clearFilters')){document.querySelectorAll('input[type=checkbox]').forEach(x=>x.checked=false);document.querySelector('#make').value='all';document.querySelector('#price').value='all';render()}if(e.target.closest('#clearCompare')){compare.clear();render();updateTray()}if(e.target.closest('#compareBtn'))toast('Comparison view is ready to explore')});
document.querySelectorAll('select,#search').forEach(x=>x.addEventListener('input',()=>{visibleCount=6;render()}));document.querySelector('#searchBtn').addEventListener('click',()=>{visibleCount=6;render();toast('Showing your best matches')});document.querySelector('#loadMore').addEventListener('click',()=>{visibleCount+=6;render();toast('More vehicles loaded')});function toast(msg){let t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}lucide.createIcons();render();
document.querySelectorAll('.main-nav a').forEach(link=>link.addEventListener('click',e=>{const target=document.querySelector(link.getAttribute('href'));if(target){e.preventDefault();target.scrollIntoView({behavior:'smooth',block:'start'});}}));
document.querySelector('.icon-btn').addEventListener('click',()=>toast('You’re all caught up'));document.querySelector('.profile-btn').addEventListener('click',()=>toast('Profile settings coming soon'));
const modal=document.querySelector('#modal');document.addEventListener('click',e=>{const d=e.target.closest('[data-details]'),c=e.target.closest('[data-contact]');if(d||c){const name=(d||c).dataset[d?'details':'contact'];document.querySelector('#modalTitle').textContent=d?'Vehicle details':'Contact dealer';document.querySelector('#modalCopy').textContent=d?`${name} is available from a verified local dealer. Contact the dealer to confirm availability and arrange a test drive.`:`Ask the dealer about ${name}, availability, financing, and a test drive.`;modal.classList.add('open');lucide.createIcons()}});document.querySelector('#modalClose').addEventListener('click',()=>modal.classList.remove('open'));modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});document.querySelector('#contactForm').addEventListener('submit',e=>{e.preventDefault();modal.classList.remove('open');e.target.reset();toast('Your enquiry was sent to the dealer')});
document.querySelector('#searchBtn').addEventListener('click',()=>document.querySelector('#inventory').scrollIntoView({behavior:'smooth',block:'start'}));
